import '@/styles/globals.css';
import Head from 'next/head';
import type { AppProps } from 'next/app';
import React from 'react';
import ym from 'react-yandex-metrika';
import { YMInitializer } from 'react-yandex-metrika';
import { Router } from 'next/router';

export default function App({ Component, pageProps, router }: AppProps) {
  Router.events.on('routeChangeComplete', (url: string) => {
    if (typeof window !== 'undefined') {
      ym('hit', url);
    }
  });

  return <>
    <Head>
      <title>MyTop - наш лучший топ!</title>
      <link rel="preconnect" href="https://ms.yandex.ru" />
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <meta property="og:url" content={process.env.NEXT_PUBLIC_DOMAIN + router.asPath} />
      <meta property="og:locale" content="ru_Ru" />
    </Head>
    <YMInitializer
      accounts={[]}
      options={{ webvisor: true, defer: true }}
      version='2'
    />
    <Component {...pageProps} />
  </>;
}
